kelola_album_song/urls.py
from django.urls import path

from kelola_album_song.views import (
    cek_royalti, create_album, create_lagu_artist, daftar_lagu,
    hapus_album, hapus_lagu, list_album, list_album_label
)

app_name = 'kelola_album_song'

urlpatterns = [
    # path('', show_main, name='show_main'),
    path('list_album/', list_album, name='list_album'),
    path('list_album_label/', list_album_label, name='list_album_label'),
    path('create_album/', create_album, name='create_album'),
    path('create_lagu_artist/<uuid:id_album>', create_lagu_artist, name='create_lagu_artist'),
    path('daftar_lagu/<str:id_album>', daftar_lagu, name='daftar_lagu'),
    path('cek_royalti/', cek_royalti, name='cek_royalti'),
    path('hapus_album/<str:id_album>', hapus_album, name='hapus_album'),
    path('hapus_lagu/<str:id_song>', hapus_lagu, name='hapus_lagu')
]

kelola_playlist/urls.py
from django.urls import path

from kelola_playlist.views import ( add_playlist, detail_playlist, playlist, add_playlist, delete_playlist, add_song_to_playlist, edit_playlist, delete_song_from_playlist, play_song, shuffle_play, play_playlist
)

app_name = 'kelola_playlist'

urlpatterns = [
    path('add_playlist/', add_playlist, name='add_playlist'),
    path('detail_playlist/<str:id_playlist>', detail_playlist, name='detail_playlist'),
    path('play_playlist/<str:id_playlist>', play_playlist, name='play_playlist'),
    path('playlist/', playlist, name='playlist'),
    path('delete_playlist/<str:id_playlist>/', delete_playlist, name='delete_playlist'),  
    path('add_song_to_playlist/<str:id_playlist>/', add_song_to_playlist, name='add_song_to_playlist'),
    path('edit_playlist/<str:id_playlist>/', edit_playlist, name='edit_playlist'),
    path('play_song/<str:id_song>/', play_song, name='play_song'),
    path('shuffle_play/<str:id_playlist>/', shuffle_play, name='shuffle_play'),
    path('delete_song_from_playlist/<str:id_playlist>/<str:id_song>/', delete_song_from_playlist, name='delete_song_from_playlist'),
]

kelola_podcast/urls.py
from django.urls import path
from .views import add_episode, add_podcast, list_podcast, podcast_detail, delete_podcast, delete_episode

app_name = 'kelola_podcast'

urlpatterns = [
    path('', list_podcast, name='list_podcast'),
    path('podcast/<uuid:id>/', podcast_detail, name='podcast_detail'),
    path('add/', add_podcast, name='add_podcast'),
     path('episode/<uuid:id>/add', add_episode, name='add_episode'),
     path('podcast/<uuid:id>/delete', delete_podcast, name='delete_podcast'),
     path('episode/<uuid:id>/delete/', delete_episode, name='delete_episode')
]

main/urls.py
from django.urls import include, path
from main.views import *

from main.views import *
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('kelola_album_song', include('kelola_album_song.urls')),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('register_label/', register_label, name='register_label'),
    path('register_pengguna/', register_pengguna, name='register_pengguna'),
    path('langganan-paket/', langganan_paket, name='langganan_paket'),
    path('downloaded-songs/', downloaded_songs, name='downloaded_songs'),
    path('pembayaran-paket/<str:jenis>/<str:harga>', pembayaran_paket, name='pembayaran_paket'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('riwayat-transaksi/', riwayat_transaksi, name='riwayat_transaksi'),
    path('logout/', logout, name='logout'),
    path('search/', search_bar, name='search_bar'),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('chart/', include('melihat_chart.urls')),
    path('podcast/', include('kelola_podcast.urls')),
    path('kelola_playlist/', include('kelola_playlist.urls')),
    path('play_user_playlist/', include('play_user_playlist.urls')),
    path('play_song/', include('play_song.urls')),
    path('kelola_album_song/', include('kelola_album_song.urls')),
]

melihat_chart/urls.py
from django.urls import include, path
from melihat_chart.views import show_daily, show_weekly

app_name = 'melihat_chart'

urlpatterns = [
    path('weekly20/', show_weekly, name='show_weekly'),
    path('daily20/', show_daily, name='show_daily')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        <style>
            body {
                background-color: rgb(247, 231, 206);
            }
        </style>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/navbar.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .navContent {
            display: flex;
        }

        .buttonnavContent {
            padding-right: 2rem; 
            margin: 5px;
        }
    </style>
    </style>

    <nav class="navbar" style="background-color: #e3f2fd;">
        <div class="container-fluid" style="margin-left: 1rem;">
            <div class="navContent">
                <a class="navbar-brand" href="">Marmut</a>
                <div class="buttonnavContent">
                    {% if not request.session.roles %}
                        <button class="btn btn-outline-dark" onclick="toLogin()">Login</button>
                        <button class="btn btn-outline-dark" onclick="toRegister()">Registrasi</button>
                    {% else %}
                        <button class="btn btn-outline-dark" onclick="toDashboard()">Dashboard</button>
                        {% if 'Label' not in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toChart()">Chart</button>
                            <button class="btn btn-outline-dark" onclick="toKelolaPlaylist()">Kelola Playlist</button>
                            <button class="btn btn-outline-dark" onclick="toSubscribe()">Langganan Paket</button>
                        {% endif %}
                        {% if 'Premium' in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toDownloadedSongs()">Downloaded songs</button>
                        {% endif %}
                        {% if 'Podcaster' in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toKelolaPodcast()">Kelola Podcast</button>
                        {% endif %}
                        {% if 'Artis' in request.session.roles or 'Songwriter' in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toAlbumSongs()">Kelola Album & Songs</button>
                        {% endif %}
                        {% if 'Label' in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toAlbumLabel()">Kelola Album</button>
                        {% endif %}
                        {% if 'Artis' in request.session.roles or 'Songwriter' in request.session.roles %}
                            <button class="btn btn-outline-dark" onclick="toRoyalti()">Cek Royalti</button>
                        {% endif %}
                            <button class="btn btn-outline-dark" onclick="toSearchPage()">Search</button>
                            <button class="btn btn-outline-dark" onclick="logoutButton()">Logout</button>
                    {% endif %}
                </div>
                </div>
            </div>
    </nav>

<script>
    function toLogin() {
        window.location.href = "{% url 'main:login' %}";
    }

    function toRegister() {
        window.location.href = "{% url 'main:register' %}"
    }

    function toDashboard() {
        window.location.href = "{% url 'main:dashboard' %}";
    }

    function toChart() {
        window.location.href = "{% url 'melihat_chart:show_daily' %}";
    }
    
    function toSearchPage() {
        window.location.href = "{% url 'main:search_bar' %}";
    }

    function toKelolaPlaylist() {
        window.location.href = "{% url 'kelola_playlist:playlist' %}";
    }

    function toSubscribe() {
        window.location.href = "{% url 'main:langganan_paket' %}";
    }
    
    function toDownloadedSongs() {
        window.location.href = "{% url 'main:downloaded_songs' %}";
    }

    function toKelolaPodcast() {
        window.location.href = "{% url 'kelola_podcast:list_podcast' %}";
    }

    function toAlbumSongs() {
        window.location.href = "{% url 'kelola_album_song:list_album' %}";
    }

    function toAlbumLabel() {
        window.location.href = "{% url 'kelola_album_song:list_album_label' %}";
    }

    function toRoyalti() {
        window.location.href = "{% url 'kelola_album_song:cek_royalti' %}";
    }

    function logoutButton() {
        window.location.href = "{% url 'main:logout' %}";
    }
</script>
{% endblock %}