kelola_playlist/urls.py
from django.urls import path

from kelola_playlist.views import ( add_playlist, detail_playlist, playlist, add_playlist, delete_playlist, add_song_to_playlist, edit_playlist, delete_song_from_playlist, play_song, shuffle_play, play_playlist
)

app_name = 'kelola_playlist'

urlpatterns = [
    path('add_playlist/', add_playlist, name='add_playlist'),
    path('detail_playlist/<str:id_playlist>', detail_playlist, name='detail_playlist'),
    path('play_playlist/<str:id_playlist>', play_playlist, name='play_playlist'),
    path('playlist/', playlist, name='playlist'),
    path('delete_playlist/<str:id_playlist>/', delete_playlist, name='delete_playlist'),  
    path('add_song_to_playlist/<str:id_playlist>/', add_song_to_playlist, name='add_song_to_playlist'),
    path('edit_playlist/<str:id_playlist>/', edit_playlist, name='edit_playlist'),
    path('play_song/<str:id_song>/', play_song, name='play_song'),
    path('shuffle_play/<str:id_playlist>/', shuffle_play, name='shuffle_play'),
    path('delete_song_from_playlist/<str:id_playlist>/<str:id_song>/', delete_song_from_playlist, name='delete_song_from_playlist'),
]

main/urls.py
from django.urls import include, path
from main.views import *

from main.views import *
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('kelola_album_song', include('kelola_album_song.urls')),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('register_label/', register_label, name='register_label'),
    path('register_pengguna/', register_pengguna, name='register_pengguna'),
    path('langganan-paket/', langganan_paket, name='langganan_paket'),
    path('downloaded-songs/', downloaded_songs, name='downloaded_songs'),
    path('pembayaran-paket/<str:jenis>/<str:harga>', pembayaran_paket, name='pembayaran_paket'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('riwayat-transaksi/', riwayat_transaksi, name='riwayat_transaksi'),
    path('logout/', logout, name='logout'),
    path('search/', search_bar, name='search_bar'),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('chart/', include('melihat_chart.urls')),
    path('podcast/', include('kelola_podcast.urls')),
    path('kelola_playlist/', include('kelola_playlist.urls')),
    path('play_user_playlist/', include('play_user_playlist.urls')),
    path('play_song/', include('play_song.urls')),
    path('kelola_album_song/', include('kelola_album_song.urls')),
]

play_song/urls.py
from django.urls import path

from play_song.views import ( song, update_song_progress, download_song,downloaded_songs, add_song_to_user_playlist, add_song_to_user_playlist_form
)

app_name = 'play_song'

urlpatterns = [
    path('song/<str:id_song>', song, name='song'),
    path('update_song_progress/<str:id_song>', update_song_progress, name='update_song_progress'),
    path('download_song/<str:id_song>/', download_song, name='download_song'),
    path('downloaded_songs/', downloaded_songs, name='downloaded_songs'),
    path('add_song_to_user_playlist_form/<str:id_song>/', add_song_to_user_playlist_form, name='add_song_to_user_playlist_form'),
    path('add_song_to_user_playlist/', add_song_to_user_playlist, name='add_song_to_user_playlist'),
]

kelola_playlist/views.py
import uuid
from django.shortcuts import redirect, render
from django.db import IntegrityError, connection
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.http import require_POST

# Create your views here.
def detail_playlist(request, id_playlist):
    if request.method == 'GET':
        if 'email' in request.session:
            user_email = request.session['email']
        
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT up.judul, a.nama, up.jumlah_lagu, up.total_durasi, up.tanggal_dibuat, up.deskripsi
                FROM USER_PLAYLIST up
                JOIN AKUN a ON up.email_pembuat = a.email
                WHERE up.id_user_playlist = %s AND a.email = %s
            """, [id_playlist, user_email])
            playlist_detail = cursor.fetchone()

        if not playlist_detail:
            return redirect('kelola_playlist:playlist')  
        
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT k.judul, ak.nama, k.durasi, k.id, ps.id_playlist
                FROM PLAYLIST_SONG ps
                JOIN KONTEN k ON ps.id_song = k.id
                JOIN SONG s ON k.id = s.id_konten
                JOIN ARTIST ar ON s.id_artist = ar.id
                JOIN AKUN ak ON ak.email = ar.email_akun
                WHERE ps.id_playlist = %s
            """, [id_playlist])
            songs = cursor.fetchall()
            print(songs)
        song_data = []
        for song in songs:
            song_data.append({
                'judul': song[0],
                'artist': song[1],
                'durasi': song[2],
                'id_song': song[3]
            })

        return render(request, 'detail_playlist.html', {
            'playlist_detail': playlist_detail,
            'songs': song_data,
            'id_playlist': id_playlist
        })

def play_playlist(request, id_playlist):
    if request.method == 'GET':
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT up.judul, a.nama, up.jumlah_lagu, up.total_durasi, up.tanggal_dibuat, up.deskripsi
                FROM USER_PLAYLIST up
                JOIN AKUN a ON up.email_pembuat = a.email
                WHERE up.id_user_playlist = %s 
            """, [id_playlist])
            playlist_detail = cursor.fetchone()

        if not playlist_detail:
            return redirect('kelola_playlist:playlist')  
        
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT k.judul, ak.nama, k.durasi, k.id
                FROM PLAYLIST_SONG ps
                JOIN KONTEN k ON ps.id_song = k.id
                JOIN SONG s ON k.id = s.id_konten
                JOIN ARTIST ar ON s.id_artist = ar.id
                JOIN AKUN ak ON ak.email = ar.email_akun
                WHERE ps.id_playlist = %s
            """, [id_playlist])
            songs = cursor.fetchall()

        song_data = []
        for song in songs:
            song_data.append({
                'judul': song[0],
                'artist': song[1],
                'durasi': song[2],
                'id_song': song[3]
            })

        return render(request, 'play_playlist.html', {
            'playlist_detail': playlist_detail,
            'songs': song_data,
            'id_playlist': id_playlist
        })
    
def playlist(request):
    if request.method == 'GET':
        if 'email' in request.session:
            user_email = request.session['email']
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT up.id_playlist, up.judul, up.jumlah_lagu, up.total_durasi
                FROM USER_PLAYLIST up
                JOIN AKUN a ON up.email_pembuat = a.email
                WHERE a.email = %s
            """, [user_email])
            playlists = cursor.fetchall()
        
        playlist_data = []
        for playlist in playlists:
            playlist_data.append({
                'id': playlist[0],
                'judul': playlist[1],
                'jumlah_lagu': playlist[2],
                'total_durasi': playlist[3]
            })
        
        return render(request, 'playlist.html', {'playlists': playlist_data})

def delete_playlist(request, id_playlist):
    if request.method == 'POST':
        if 'email' in request.session:
            user_email = request.session['email']
        with connection.cursor() as cursor:
            cursor.execute("""
                DELETE FROM USER_PLAYLIST
                WHERE id_user_playlist = %s AND email_pembuat = %s
            """, [id_playlist, user_email])
        
        return redirect('kelola_playlist:playlist')
    
def add_playlist(request):
    if request.method == 'POST':
        judul = request.POST['judul']
        deskripsi = request.POST['deskripsi']
        user_email = request.session.get('email')

        if not user_email:
            return redirect('login.html')

        id_playlist = str(uuid.uuid4())

        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO PLAYLIST (id)
                VALUES (%s)
            """, [id_playlist])

            cursor.execute("""
                INSERT INTO USER_PLAYLIST (id_user_playlist, judul, deskripsi, email_pembuat, jumlah_lagu, total_durasi, tanggal_dibuat, id_playlist)
                VALUES (%s, %s, %s, %s, %s, %s, NOW(), %s)
            """, [id_playlist, judul, deskripsi, user_email, 0, 0, id_playlist])
        
        return redirect('kelola_playlist:playlist')
    return render(request, 'add_playlist.html')

def edit_playlist(request, id_playlist):
    if request.method == 'GET':
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT up.judul, up.deskripsi
                FROM USER_PLAYLIST up
                WHERE up.id_user_playlist = %s
            """, [id_playlist])
            playlist = cursor.fetchone()

        if not playlist:
            return redirect('kelola_playlist:playlist') 

        return render(request, 'edit_playlist.html', {
            'id_playlist': id_playlist,
            'judul': playlist[0],
            'deskripsi': playlist[1],
        })

    elif request.method == 'POST':
        judul = request.POST.get('judul')
        deskripsi = request.POST.get('deskripsi')

        if not judul or not deskripsi:
            return render(request, 'edit_playlist.html', {
                'id_playlist': id_playlist,
                'judul': judul,
                'deskripsi': deskripsi,
                'error': 'Judul and Deskripsi are required'
            })

        with connection.cursor() as cursor:
            cursor.execute("""
                UPDATE USER_PLAYLIST
                SET judul = %s, deskripsi = %s
                WHERE id_user_playlist = %s
            """, [judul, deskripsi, id_playlist])

        return redirect(reverse('kelola_playlist:detail_playlist', args=[id_playlist]))
    
def get_songs():
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT k.judul, ak.nama, k.id
            FROM KONTEN k
            JOIN SONG s ON k.id = s.id_konten
            JOIN ARTIST ar ON s.id_artist = ar.id
            JOIN AKUN ak ON ak.email = ar.email_akun
        """)
        songs = cursor.fetchall()
    return [
        {'judul': song[0], 'artist': song[1], 'id': song[2]}
        for song in songs
    ]

def add_song_to_playlist(request, id_playlist):
    if request.method == 'GET':
        print(f"GET request received for playlist ID: {id_playlist}")
        songs = get_songs()
        return render(request, 'add_song.html', {
            'id_playlist': id_playlist,
            'songs': songs
        })

    elif request.method == 'POST':
        print(f"POST request received for playlist ID: {id_playlist}")
        song_id = request.POST.get('song_id')
        print(f"Song ID from POST request: {song_id}")

        if not song_id:
            print("Song ID is required but not provided.")
            songs = get_songs()
            return render(request, 'add_song.html', {
                'id_playlist': id_playlist,
                'songs': songs,
                'error': 'Song ID is required'
            })

        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT id
                FROM PLAYLIST, USER_PLAYLIST
                WHERE id_user_playlist = %s AND id_playlist = id
            """, [id_playlist])
            playlist_exists = cursor.fetchone()[0]
            print(f"Playlist exists: {playlist_exists}")

            if not playlist_exists:
                print(f"Playlist with ID {id_playlist} does not exist.")
                songs = get_songs()
                return render(request, 'add_song.html', {
                    'id_playlist': id_playlist,
                    'songs': songs,
                    'error': 'Playlist does not exist'
                })

            cursor.execute("""
                SELECT COUNT(*)
                FROM PLAYLIST_SONG
                WHERE id_playlist = %s AND id_song = %s
            """, [id_playlist, song_id])
            count = cursor.fetchone()[0]
            print(f"Song already in playlist: {count > 0}")

            if count > 0:
                return render(request, 'message.html', {
                'message': f"Lagu dengan judul sudah ada di playlist!",
                'options': [
                    {'label': 'KE PLAYLIST', 'url': reverse('kelola_playlist:detail_playlist', args=[id_playlist])}
                ]
            })
               
            try:
                with connection.cursor() as cursor:
                    cursor.execute("""
                        INSERT INTO PLAYLIST_SONG (id_playlist, id_song)
                        VALUES (%s, %s)

kelola_playlist/templates/add_playlist.html
{% extends 'base.html' %}


{% block content %}
{% include 'navbar.html' %}
    <style>
        body {
            background-color: rgb(247, 231, 206);
        }
        .brand {
            font-size: 20px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 30px;
        }
        .background-container {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }
        .centered-text {
            text-align: center;
        }
    </style>
    <div class="container">
        <div class="row justify-content-center align-items-top min-vh-100">
            <div class="col-md-6">
                <div class="background-container mt-4">
    
                <h1 class="centered-text mb-4">Tambah Playlist</h1>
    
                <form>
                    <div class="form-group">
                        <label for="judul">Judul:</label>
                        <input type="text" id="judul" name="judul" class="form-control" placeholder="Masukkan judul playlist">
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi:</label>
                        <textarea id="deskripsi" name="deskripsi" class="form-control" placeholder="Masukkan deskripsi playlist"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </form>
            </div>
            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

kelola_playlist/templates/add_song.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-color: rgb(247, 231, 206);
    }
    .custom-padding {
        padding-right: 10px;
    }
    .name-class {
        margin-right: 10px;
    }
    .background-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .form-label {
        font-weight: bold;
    }
</style>

<div class="container mt-5 background-container">
    <h1 class="mb-3 centered-text">Tambah Lagu</h1>
    <form method="post" action="{% url 'kelola_playlist:add_song_to_playlist' id_playlist %}">
        {% csrf_token %}
        <input type="hidden" name="id_playlist" value="{{ id_playlist }}">
        <div class="form-group">
            <label for="song" class="form-label">Pilih Lagu:</label>
            <select class="form-control" id="song" name="song_id" required>
                {% for song in songs %}
                    <option value="{{ song.id }}">{{ song.judul }} by {{ song.artist }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Tambah</button>
    </form>
</div>

{% endblock content %}

kelola_playlist/templates/detail_playlist.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>User Playlist Detail</title>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-color: rgb(247, 231, 206);
    }
    .custom-padding {
        padding-right: 10px;
    }
    
    .name-class {
        margin-right: 10px;
    }
    .background-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
    }
    table, th, td {
        border: 1.5px solid #dedddd;
        vertical-align: middle;
        padding: 10px;
        font-weight: 600;
    }
    th {
        background-color: #151414;
        color: #f7f7f7;
        text-align: center;
        font-weight: bold;
    }
    td {
        vertical-align: top;
    }
    tr {
        background-color: #f2f2f2;
    }
    .centered-text {
        text-align: center;
    }
</style>

<div class="container mt-5 background-container">
    <h1 class="mb-3 centered-text">User Playlist Detail</h1>
    <div>
        <h4>Judul: {{ playlist_detail.0 }}</h4>
        <p>Pembuat: {{ playlist_detail.1 }}</p>
        <p>Jumlah Lagu: {{ playlist_detail.2 }}</p>
        <p>Total Durasi: {{ playlist_detail.3 }} menit</p>
        <p>Tanggal Dibuat: {{ playlist_detail.4 }}</p>
        <p>Deskripsi: {{ playlist_detail.5 }}</p>
    </div>
    <div class="mt-3 mb-3">
        <div class="text-center">
            <div class="btn-toolbar justify-content-center" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <button class="btn btn-primary btn-action">Shuffle Play</button>
                </div>
            </div>
            <div class="btn-toolbar justify-content-center" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <a href="{% url 'kelola_playlist:playlist' %}" class="btn btn-secondary btn-action mt-2 mb-4">Kembali</a>
                </div>
            </div>
        </div>
    </div>
    <h5 class="centered-text">DAFTAR LAGU</h5>
    <table>
        <thead>
            <tr>
                <th>Judul Lagu</th>
                <th>Oleh</th>
                <th>Durasi</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for song in songs %}
            <tr>
                <td>{{ song.judul }}</td>
                <td>{{ song.artist }}</td>
                <td>{{ song.durasi }} menit</td>
                <td>
                    <a href="#" class="btn btn-info btn-action">Lihat</a>
                    <a href="#" class="btn btn-success btn-action">Play</a>
                    <a href="#" class="btn btn-danger btn-action">Hapus</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="modal fade" id="tambahLaguModal" tabindex="-1" role="dialog" aria-labelledby="tambahLaguModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="tambahLaguModalLabel">Tambah Lagu ke Playlist</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="tambahLaguForm">
                        <div class="form-group">
                            <label for="laguSelect">Lagu:</label>
                            <select class="form-control" id="laguSelect" required>
                                <option value="" disabled selected>Pilih Lagu</option>
                                <option value="Song5 - Artis5">Song5 - Artis5</option>
                                <option value="Song6 - Artis6">Song6 - Artis6</option>
                                <option value="Song7 - Artis7">Song7 - Artis7</option>
                                <option value="Song8 - Artis8">Song8 - Artis8</option>
                            </select>
                        </div>
                    </form>
                    <div class="mt-3 mb-3">
                        <div class="text-center">
                            <div class="btn-toolbar justify-content-center" role="toolbar">
                                <div class="btn-group mr-2" role="group">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal">Submit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3 mb-3">
        <div class="text-center">
            <div class="btn-toolbar justify-content-center" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <button class="btn btn-success mt-3" data-toggle="modal" data-target="#tambahLaguModal">Tambah Lagu</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

kelola_playlist/templates/edit_playlist.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-color: rgb(247, 231, 206);
    }
    .custom-padding {
        padding-right: 10px;
    }
    .name-class {
        margin-right: 10px;
    }
    .background-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .form-label {
        font-weight: bold;
    }
</style>

<div class="container mt-5 background-container">
    <h1 class="mb-3 centered-text">Ubah Playlist</h1>
    <form method="post" action="{% url 'kelola_playlist:edit_playlist' id_playlist %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="judul" class="form-label">Judul Playlist:</label>
            <input type="text" class="form-control" id="judul" name="judul" value="{{ judul }}" required>
        </div>
        <div class="form-group">
            <label for="deskripsi" class="form-label">Deskripsi Playlist:</label>
            <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" required>{{ deskripsi }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Ubah</button>
    </form>
</div>

{% endblock content %}

kelola_playlist/templates/play_playlist.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>User Playlist Detail</title>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-color: rgb(247, 231, 206);
    }
    .custom-padding {
        padding-right: 10px;
    }
    
    .name-class {
        margin-right: 10px;
    }
    .background-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
    }
    table, th, td {
        border: 1.5px solid #dedddd;
        vertical-align: middle;
        padding: 10px;
        font-weight: 600;
    }
    th {
        background-color: #151414;
        color: #f7f7f7;
        text-align: center;
        font-weight: bold;
    }
    td {
        vertical-align: top;
    }
    tr {
        background-color: #f2f2f2;
    }
    .centered-text {
        text-align: center;
    }
</style>

<div class="container mt-5 background-container">
    <h1 class="mb-3 centered-text">User Playlist Detail</h1>
    <div>
        <h4>Judul: {{ playlist_detail.0 }}</h4>
        <p>Pembuat: {{ playlist_detail.1 }}</p>
        <p>Jumlah Lagu: {{ playlist_detail.2 }}</p>
        <p>Total Durasi: {{ playlist_detail.3 }} menit</p>
        <p>Tanggal Dibuat: {{ playlist_detail.4 }}</p>
        <p>Deskripsi: {{ playlist_detail.5 }}</p>
    </div>
    <div class="mt-3 mb-3">
        <div class="text-center">
            <div class="btn-toolbar justify-content-center" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <form action="{% url 'kelola_playlist:shuffle_play' id_playlist %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-action">Shuffle Play</button>
                    </form>
                </div>
            </div>
            <div class="btn-toolbar justify-content-center" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <a href="{% url 'kelola_playlist:playlist' %}" class="btn btn-secondary btn-action mt-2 mb-4">Kembali</a>
                </div>
            </div>
        </div>
    </div>
    {% if songs %}
    <h5 class="centered-text">DAFTAR LAGU</h5>
    <table>
        <thead>
            <tr>
                <th>Judul Lagu</th>
                <th>Oleh</th>
                <th>Durasi</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for song in songs %}
            <tr>
                <td>{{ song.judul }}</td>
                <td>{{ song.artist }}</td>
                <td>{{ song.durasi }} menit</td>
                <td>
                    <a href="{% url 'play_song:song' song.id_song %}" class="btn btn-info btn-action">Lihat</a>
                    <a href="{% url 'kelola_playlist:play_song' song.id_song %}" class="btn btn-success btn-action">Play</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h5 class="centered-text mb-3">Belum Ada Lagu</h5>
    {% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock content %}

kelola_playlist/templates/playlist.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    body {
        background-color: rgb(247, 231, 206);
    }
    .custom-padding {
        padding-right: 10px;
    }
    .name-class {
        margin-right: 10px;
    }
    .background-container {
        background-color: #ffffff;
        border-radius: 10px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
    }
    table, th, td {
        border: 1.5px solid #dedddd;
        vertical-align: middle;
        padding: 10px;
        font-weight: 600;
    }
    th {
        background-color: #151414;
        color: #f7f7f7;
        text-align: center;
        font-weight: bold;
    }
    td {
        vertical-align: top;
    }
    tr {
        background-color: #f2f2f2;
    }
    .centered-text {
        text-align: center;
    }
</style>

<div class="container mt-5 background-container">
    <h1 class="mb-3 centered-text">User Playlist</h1>
    {% if error %}
        <p>{{ error }}</p>
    {% endif %}
    {% if playlists %}
    <table>
        <thead>
            <tr>
                <th>Judul</th>
                <th>Jumlah Lagu</th>
                <th>Total Durasi</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="table-group-divider last-table">
            {% for playlist in playlists %}
            <tr>
                <td>{{ playlist.judul }}</td>
                <td>{{ playlist.jumlah_lagu }}</td>
                <td>{{ playlist.total_durasi }} menit</td>
                <td>
                    <a href="{% url 'kelola_playlist:detail_playlist' playlist.id %}" class="btn btn-info btn-action">Detail</a>
                    <a href="{% url 'kelola_playlist:edit_playlist' playlist.id %}" class="btn btn-warning btn-action">Ubah</a>
                    <form action="{% url 'kelola_playlist:delete_playlist' playlist.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-action">Hapus</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h5 class="centered-text mb-3">Anda Belum Memiliki Playlist</h5>
    {% endif %}
    <div class="btn-toolbar justify-content-center" role="toolbar">
        <div class="btn-group mr-2" role="group">
            <a href="{% url 'kelola_playlist:add_playlist'%}" class="btn btn-success mt-3">Tambah Playlist</a>
        </div>
    </div>
</div>

{% endblock content %}