kelola_playlist/urls.py
from django.urls import path

from kelola_playlist.views import ( add_playlist, detail_playlist, playlist, add_playlist, delete_playlist, add_song_to_playlist, edit_playlist, delete_song_from_playlist, play_song, shuffle_play, play_playlist
)

app_name = 'kelola_playlist'

urlpatterns = [
    path('add_playlist/', add_playlist, name='add_playlist'),
    path('detail_playlist/<str:id_playlist>', detail_playlist, name='detail_playlist'),
    path('play_playlist/<str:id_playlist>', play_playlist, name='play_playlist'),
    path('playlist/', playlist, name='playlist'),
    path('delete_playlist/<str:id_playlist>/', delete_playlist, name='delete_playlist'),  
    path('add_song_to_playlist/<str:id_playlist>/', add_song_to_playlist, name='add_song_to_playlist'),
    path('edit_playlist/<str:id_playlist>/', edit_playlist, name='edit_playlist'),
    path('play_song/<str:id_song>/', play_song, name='play_song'),
    path('shuffle_play/<str:id_playlist>/', shuffle_play, name='shuffle_play'),
    path('delete_song_from_playlist/<str:id_playlist>/<str:id_song>/', delete_song_from_playlist, name='delete_song_from_playlist'),
]

kelola_podcast/urls.py
from django.urls import path
from .views import add_episode, add_podcast, list_podcast, podcast_detail, delete_podcast, delete_episode

app_name = 'kelola_podcast'

urlpatterns = [
    path('', list_podcast, name='list_podcast'),
    path('podcast/<uuid:id>/', podcast_detail, name='podcast_detail'),
    path('add/', add_podcast, name='add_podcast'),
     path('episode/<uuid:id>/add', add_episode, name='add_episode'),
     path('podcast/<uuid:id>/delete', delete_podcast, name='delete_podcast'),
     path('episode/<uuid:id>/delete/', delete_episode, name='delete_episode')
]

main/urls.py
from django.urls import include, path
from main.views import *

from main.views import *
app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('kelola_album_song', include('kelola_album_song.urls')),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('register_label/', register_label, name='register_label'),
    path('register_pengguna/', register_pengguna, name='register_pengguna'),
    path('langganan-paket/', langganan_paket, name='langganan_paket'),
    path('downloaded-songs/', downloaded_songs, name='downloaded_songs'),
    path('pembayaran-paket/<str:jenis>/<str:harga>', pembayaran_paket, name='pembayaran_paket'),
    path('melihat-chart/', melihat_chart, name='melihat_chart'),
    path('riwayat-transaksi/', riwayat_transaksi, name='riwayat_transaksi'),
    path('logout/', logout, name='logout'),
    path('search/', search_bar, name='search_bar'),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete_song/<str:song_id>/', delete_song, name='delete_song'),
]

marmut/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('chart/', include('melihat_chart.urls')),
    path('podcast/', include('kelola_podcast.urls')),
    path('kelola_playlist/', include('kelola_playlist.urls')),
    path('play_user_playlist/', include('play_user_playlist.urls')),
    path('play_song/', include('play_song.urls')),
    path('kelola_album_song/', include('kelola_album_song.urls')),
]

melihat_chart/urls.py
from django.urls import include, path
from melihat_chart.views import show_daily, show_weekly

app_name = 'melihat_chart'

urlpatterns = [
    path('weekly20/', show_weekly, name='show_weekly'),
    path('daily20/', show_daily, name='show_daily')
]

play_song/urls.py
from django.urls import path

from play_song.views import ( song, update_song_progress, download_song,downloaded_songs, add_song_to_user_playlist, add_song_to_user_playlist_form
)

app_name = 'play_song'

urlpatterns = [
    path('song/<str:id_song>', song, name='song'),
    path('update_song_progress/<str:id_song>', update_song_progress, name='update_song_progress'),
    path('download_song/<str:id_song>/', download_song, name='download_song'),
    path('downloaded_songs/', downloaded_songs, name='downloaded_songs'),
    path('add_song_to_user_playlist_form/<str:id_song>/', add_song_to_user_playlist_form, name='add_song_to_user_playlist_form'),
    path('add_song_to_user_playlist/', add_song_to_user_playlist, name='add_song_to_user_playlist'),
]

melihat_chart/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.db import connection
import uuid
import random
import datetime
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from django.db import IntegrityError



# Create your views here.
def show_main(request):
    return render(request, "main.html")

def logout(request):
    try:
        del request.session['email']
        del request.session['roles']
    except KeyError:
        pass
    return redirect('main:login')

def authenticate(email, password):
    # print(f"cek email {email}")
    # print(f"cek password {password}")
    with connection.cursor() as cursor:
        cursor.execute("SELECT password FROM AKUN WHERE email = %s", [email])
        row = cursor.fetchone()
        print(row)
    
    if row is None:
        print(f"No user found with email: {email}")
        return None  # User does not exist

    stored_password = row[0]
    # print(stored_password)
    if password == stored_password:
        # print("Password match!")
        return email  # Authentication successful
    else:
        # print("Password does not match")
        return None  # Authentication failed

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        roles = []
        
        user = authenticate(email, password)
        roles = []
        user_info = {}
        if user is not None:
            with connection.cursor() as cursor:
                cursor.execute("SELECT nama, kota_asal, gender, tempat_lahir, tanggal_lahir FROM AKUN WHERE email = %s", [email])
                user_info_row = cursor.fetchone()
                user_info = {
                    'nama': user_info_row[0],
                    'kota_asal': user_info_row[1],
                    'gender': 'Laki-laki' if user_info_row[2] == 1 else 'Perempuan',
                    'tempat_lahir': user_info_row[3],
                    'tanggal_lahir': user_info_row[4].strftime('%Y-%m-%d')  # Convert date to string
                }
            
            with connection.cursor() as cursor:
                cursor.execute("SELECT EMAIL FROM PODCASTER WHERE email = %s", [email])
                row = cursor.fetchone()
                if row and row[0] == email:
                    roles.append('Podcaster')

            with connection.cursor() as cursor:
                cursor.execute("SELECT email_akun FROM ARTIST WHERE email_akun = %s", [email])
                row = cursor.fetchone()
                if row and row[0] == email:
                    roles.append('Artis')

            with connection.cursor() as cursor:
                cursor.execute("SELECT email_akun FROM SONGWRITER WHERE email_akun = %s", [email])
                row = cursor.fetchone()
                if row and row[0] == email:
                    print('masok')
                    roles.append('Songwriter')

            with connection.cursor() as cursor:
                cursor.execute("SELECT EMAIL FROM LABEL WHERE email = %s", [email])
                row = cursor.fetchone()
                if row and row[0] == email:
                    roles.append('Label')

            with connection.cursor() as cursor:
                cursor.execute("SELECT EMAIL FROM PREMIUM WHERE email = %s", [email])
                row = cursor.fetchone()
                if row and row[0] == email:
                    roles.append('Premium')
                else:
                    roles.append('Pengguna Biasa')
            print(user_info)

            request.session['email'] = user
            request.session['roles'] = roles
            request.session['user_info'] = user_info

            return redirect('main:dashboard')
        else:
            return HttpResponse("Invalid credentials")

    return render(request, 'login.html')

def dashboard(request):
    email = request.session.get('email')
    roles = request.session.get('roles', [])
    podcasts = []
    songs = []
    albums = []
    playlists = []

    with connection.cursor() as cursor:
        if 'Podcaster' in roles:
            cursor.execute("""
                SELECT k.id, k.judul 
                FROM podcast p 
                JOIN konten k ON p.id_konten = k.id 
                WHERE p.email_podcaster = %s
            """, [email])
            podcasts = cursor.fetchall()

        if 'Artis' in roles or 'Songwriter' in roles:
            cursor.execute("""
                SELECT k.id, k.judul 
                FROM song s 
                JOIN konten k ON s.id_konten = k.id 
                WHERE s.id_artist = (SELECT id FROM artist WHERE email_akun = %s)
            """, [email])
            songs = cursor.fetchall()

        if 'Label' in roles:
            cursor.execute("""
                SELECT a.id, a.judul 
                FROM album a 
                WHERE a.id_label = (SELECT id FROM label WHERE email = %s)
            """, [email])
            albums = cursor.fetchall()

        cursor.execute("""
            SELECT up.id_user_playlist, up.judul 
            FROM user_playlist up 
            WHERE up.email_pembuat = %s
        """, [email])
        playlists = cursor.fetchall()

    context = {
        'podcasts': podcasts,
        'songs': songs,
        'albums': albums,
        'playlists': playlists,
    }

    return render(request, 'dashboard.html', context)


def register(request):
    return render (request, 'register.html')

def register_label(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        nama = request.POST.get('nama')
        kontak = request.POST.get('kontak')
        uuid_label = uuid.uuid4()

        with connection.cursor() as cursor:
            cursor.execute("SELECT EMAIL FROM LABEL WHERE EMAIL = %s", email)
            row = cursor.fetchone()

        if row == email:
            return HttpResponse("Email Already Exist")

        rate_royalti = random.randint(10_000, 100_000)
        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO PEMILIK_HAK_CIPTA (id, rate_royalti)
                VALUES (%s, %s)
            """, [uuid_label, rate_royalti])

        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO LABEL (id, nama, email, kontak, id_pemilik_hak_cipta, password)
                VALUES (%s, %s, %s, %s, %s, %s)
            """, [uuid_label, nama, email, kontak, uuid_label, password])
        return redirect('main:login')

    return render (request, 'register_label.html')

def register_pengguna(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        nama = request.POST.get('nama')
        gender = request.POST.get('gender')
        if gender == "Laki-laki":
            gender = 1
        else :
            gender = 0
        tempat_lahir = request.POST.get('tempatLahir')
        tanggal_lahir = request.POST.get('tanggalLahir')
        kota_asal = request.POST.get('kotaAsal')
        roles = request.POST.getlist('role')

        with connection.cursor() as cursor:
            cursor.execute("SELECT EMAIL FROM AKUN WHERE email = %s", [email])
            row = cursor.fetchone()
        if row != None :
            return HttpResponse("Email Already Registered")
        else :
            if len(roles) == 0:
                is_verified = False
            else: 
                is_verified = True
            with connection.cursor() as cursor:
                cursor.execute("""
                    INSERT INTO AKUN (email, password, nama, gender, tempat_lahir, tanggal_lahir, is_verified, kota_asal)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """, [email, password, nama, gender, tempat_lahir, tanggal_lahir, is_verified, kota_asal])
            if len(roles) > 0 :
                new_uuid = uuid.uuid4()
                    
                rate_royalti = random.randint(1_000_000, 100_000_000)
                pemilik_created = False
                for role in roles: 
                    role = role.upper()
                    if(role == "PODCASTER"):
                        with connection.cursor() as cursor:
                            cursor.execute("""
                                INSERT INTO PODCASTER (email)
                                VALUES (%s)
                            """, [email])
                    if(role == "ARTIST" or role == "SONGWRITER"):
                        if pemilik_created == False:
                            with connection.cursor() as cursor:
                                cursor.execute("""
                                    INSERT INTO PEMILIK_HAK_CIPTA (id, rate_royalti)
                                    VALUES (%s, %s)
                                """, [new_uuid, rate_royalti])
                            pemilik_created = True
                        if(role == "ARTIST"):
                            with connection.cursor() as cursor:
                                cursor.execute("""
                                    INSERT INTO ARTIST (id, email_akun, id_pemilik_hak_cipta)
                                    VALUES (%s, %s, %s)
                                """, [new_uuid, email, new_uuid])
                        else:
                            with connection.cursor() as cursor:
                                cursor.execute("""
                                    INSERT INTO SONGWRITER (id, email_akun, id_pemilik_hak_cipta)
                                    VALUES (%s, %s, %s)
                                """, [new_uuid, email, new_uuid])

melihat_chart/views.py
from django.db import connection
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
# Create your views here.
def show_weekly(request):
    now = datetime.now()
    print(now)
    last_week = now - timedelta(days=7)

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT k.id, k.judul, k.tanggal_rilis, COUNT(aps.id_song) AS total_play, a.nama
            FROM akun_play_song aps
            JOIN song s ON aps.id_song = s.id_konten
            JOIN konten k ON s.id_konten = k.id
            JOIN artist ar ON s.id_artist = ar.id
            JOIN akun a ON ar.email_akun = a.email
            WHERE aps.waktu >= %s AND aps.waktu <= %s
            GROUP BY k.id, k.judul, k.tanggal_rilis, a.nama
            ORDER BY total_play DESC
            LIMIT 20
        """, [last_week, now])
        songs = cursor.fetchall()
    
    context = {
        'songs': songs
    }
    
    return render(request, "weekly20.html", context)

def show_daily(request):
    now = datetime.now()
    last_24_hours = now - timedelta(days=1)

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT k.id, k.judul, k.tanggal_rilis, COUNT(aps.id_song) AS total_play, a.nama
            FROM akun_play_song aps
            JOIN song s ON aps.id_song = s.id_konten
            JOIN konten k ON s.id_konten = k.id
            JOIN artist ar ON s.id_artist = ar.id
            JOIN akun a ON ar.email_akun = a.email
            WHERE aps.waktu >= %s AND aps.waktu <= %s
            GROUP BY k.id, k.judul, k.tanggal_rilis, a.nama
            ORDER BY total_play DESC
            LIMIT 20
        """, [last_24_hours, now])
        songs = cursor.fetchall()
    
    context = {
        'songs': songs
    }
    
    return render(request, "daily20.html", context)

main/templates/downloaded_songs.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}
<style>
    .outerDiv {
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 2rem;
        text-align: center;
    }
</style>
<div class="outerDiv">
    <div>
        <h2 style="text-align: center;padding-bottom: 1rem;">Downloaded Songs</h2>
        {% if data %}
        <table class="table">
            <thead>
                <tr>
                    <th>Judul Lagu</th>
                    <th>Oleh</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for d in data %}
                <tr data-id="{{ d.id }}">
                    <td>{{ d.judul }}</td>
                    <td>{{ d.nama }}</td>
                    <td>
                        <a href="{% url 'play_song:song' d.id %}" class="btn btn-info btn-action">Lihat</a>
                        <button class="btn btn-outline-danger hapus" onclick="deleteSong('{{d.id}}','{{d.nama}}')">Hapus</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>Belum ada lagu yang didownload</h4>
        {% endif %}
        <input
            class="btn btn-outline-dark"
            action="action"
            onclick="window.history.go(-1); return false;"
            type="submit"
            value="Kembali"
        />
    </div>
</div>
<script>

    function deleteSong(songId, songTitle) {
        fetch(`/delete_song/${songId}/`, {
            method: 'DELETE',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                alert("Berhasil menghapus Lagu dengan judul " + songTitle + " dari daftar unduhan!");
                document.querySelector(`tr[data-id="${songId}"]`).remove();
            } else {
                alert("Gagal menghapus lagu.");
            }
        })
        .catch(error => {
            console.error("Error deleting song:", error);
            alert("Terjadi kesalahan saat menghapus lagu.");
        });
    }

    document.addEventListener("DOMContentLoaded", function() {
        var deleteButtons = document.querySelectorAll(".hapus");

        deleteButtons.forEach(function(button) {
            button.addEventListener("click", function() {
                var row = this.closest("tr");
                var songId = row.getAttribute("data-id");
                var songTitle = row.querySelector(".judul").value;
                deleteSong(songId, songTitle);
            });
        });
    });
</script>
{% endblock content %}

main/templates/langganan_paket.html
{% extends 'base.html' %}


{% block content %}
{% include 'navbar.html' %}
<style>
    .allCard {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

</style>
    <div class="d-flex justify-content-center align-items-center" style="width: 100vw; height: 80vh;">
        {% for data in paket %}
        <form method="POST" style="display: block; margin-bottom: 10px;">
            {% csrf_token %}
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h3>Premium</h3>
                    <h5>{{ data.jenis }}</h5>
                    <h5>{{ data.harga }}</h5>
                    <input type="hidden" name="selected_jenis" value="{{ data.jenis }}">
                    <input type="hidden" name="selected_harga" value="{{ data.harga }}">
                    <input class="btn login_btn btn-outline-dark" type="submit" value="{{ data.jenis }}">
                </div>
            </div>
        </form>
        {% endfor %}
        <button class="btn login_btn btn-outline-dark" type="submit" style="display: block;" onclick="toHistory()"> Riwayat Transaksi</button>
    </div>
<script>

    function toHistory() {
        window.location.href = "{% url 'main:riwayat_transaksi' %}";
    }
</script>
{% endblock content %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class = "d-flex justify-content-center align-items-center" style="min-height: 100vh;min-width: 100vw;background-color: #F0F0F0;">
    <div class = "login shadow p-4 mb-5 bg-body rounded" style="width: 25rem;margin-bottom: 5rem;">
    
        <h1 class="text-center">Login</h1>
        <br>
    
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Email: </td>
                    <td><input style="margin-left: 0.8rem;" type="text" name="email" placeholder="Email" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input style="margin-left: 0.8rem;" type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

            </table>
            <div class="text-center" style="margin: 0.6rem;">   
                <input class="btn login_btn btn-outline-dark" type="submit" value="Login">
            </div>
        </form>
            
        <p class="text-center">Don't have an account yet? <a class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'main:register' %}">Register Now</a></p>
    
    </div>
</div>

{% endblock content %}

main/templates/melihat_chart.html
{% extends 'base.html' %}


{% block content %}
{% include 'navbar.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" crossorigin="anonymous">
    <title>Marmut | Charts</title>
    <style>
        body {
            background-color: rgb(247, 231, 206);
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <!-- Part 1: Title -->
        <div class="d-flex justify-content-between align-items-center mb-5">
            <h1>Marmut | Charts</h1>
            <a href="{% url 'main:dashboard' %}" class="btn btn-secondary">Back</a>
        </div>
        

        <!-- Part 2: Cards Container -->
        <div class="d-flex flex-column flex-sm-row justify-content-between">
            <!-- Card for Daily Top 20 -->
            <div class="card mb-3 mb-sm-0" style="flex-grow: 1; margin-right: 10px;">
                <div class="card-body">
                    <h5 class="card-title">Daily Top 20</h5>
                    <img src="https://cdn-icons-png.flaticon.com/512/4868/4868706.png" alt="Daily Top 20 Icon" style="width: 100%; max-width: 128px; height: auto; display: block; margin: 0 auto;">
                    <p class="card-text mt-5">Dapatkan update harian lagu-lagu populer dengan Daily Top 20 di Aplikasi Marmut. Nikmati alunan musik terkini dan favorit Anda setiap hari. Sambut setiap momen dengan soundtrack terbaik, hanya di Marmut!</p>
                    <a href="{% url 'melihat_chart:show_daily' %}" class="btn btn-outline-warning">Daily Top 20</a>
                </div>
            </div>

            <!-- Card for Weekly Top 20 -->
            <div class="card" style="flex-grow: 1; margin-left: 10px;">
                <div class="card-body">
                    <h5 class="card-title">Weekly Top 20</h5>
                    <img src="https://cdn-icons-png.flaticon.com/256/2282/2282457.png" alt="Weekly Top 20 Icon" style="width: 100%; max-width: 128px; height: auto; display: block; margin: 0 auto;">
                    <p class="card-text mt-5">Temukan lagu-lagu teratas minggu ini dengan Weekly Top 20 di Aplikasi Marmut. Dengarkan seleksi terbaik yang telah kami kurasi untuk menemani minggu Anda. Jangan lewatkan hits mingguan,hanya di Marmut!</p>
                    <a href="{% url 'melihat_chart:show_weekly' %}" class="btn btn-outline-primary">Weekly Top 20</a>
                </div>
            </div>
        </div>

        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
    </div>
</body>
</html>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
    <style>
        body {
            background-color: rgb(247, 231, 206);
        }

        .brand {
            font-size: 20px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 30px;
        }

        .background-container {
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            max-width: 400px;
            margin: 0 auto;
            padding: 60px;
        }

        .center-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .centered-text {
            text-align: center;
        }

        .btn-success {
            width: 200px; 
        }
    </style>
<div class="container mt-4">
    <div class="row justify-content-center align-items-top">
        <div class="col-md-6">
            <div class="main background-container">
                <h1 class="centered-text mb-4">Register</h1>
                <button type="submit" class="btn btn-primary btn-block mt-4" onclick="toRegisPengguna()">Pengguna</button><br>
                <button type="submit" class="btn btn-primary btn-block mt-2" onclick="toRegisLabel()">Label</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function toRegisPengguna() {
        window.location.href = "{% url 'main:register_pengguna' %}";
    }

    function toRegisLabel() {
        window.location.href = "{% url 'main:register_label' %}"
    }
</script>
{% endblock content %}

main/templates/riwayat_transaksi.html
{% extends 'base.html' %}


{% block content %}
<style>
    .content {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }

    .table-transaksi {
        margin-top: 5rem;
    }
</style>
{% include 'navbar.html' %}
<div class="content">
    <h2 style="text-align: center;padding-top: 3rem;">RIWAYAT TRANSAKSI PAKET</h2>
    <div class="table-transaksi">
        <table class="table">
            <th>Jenis</th>
            <th>Tanggal Dimulai</th>
            <th>Tanggal Berakhir</th>
            <th>Metode Pembayaran</th>
            <th>Nominal</th>
            <tr>
                <td>{{ jenis }}</td>
                <td>{{ tanggal_mulai }}</td>
                <td>{{ tanggal_akhir }}</td>
                <td>{{ metode_pembayaran }}</td>
                <td>Rp {{ nominal }}</td>
            </tr>
        </table>
    </div>
    <button class="btn btn-outline-dark" onclick="toSubscribe()">Kembali</button>
</div>

<script>
    function toSubscribe() {
        window.location.href = "{% url 'main:langganan_paket' %}";
    }
</script>
{% endblock content %}

main/templates/search_page.html
{% extends 'base.html' %}

{% block meta %}
    <title>Search Page</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<style>
    .result-box {
        width: 40vw;
        height: 50vh;
        border: 3px solid #ccc;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: flex-start;
        text-align: center;
        overflow-y: auto;
        overflow-x: hidden;
    }
    .table {
        width: 100%;
        margin: auto;
    }
</style>

<div class="d-flex justify-content-center flex-column" style="min-height: max-content; min-width: max-content; margin-top: 2rem;">
    <form class="d-flex flex-column justify-content-center" style="width: fit-content; margin: auto;" role="search" method="GET" action="{% url 'main:search_bar' %}">
        <h4 style="text-align: center; margin-bottom: 0.5rem;">Search Here!</h4>
        <input class="form-control me-2" style="margin-bottom: 0.5rem;" type="search" name="search" placeholder="Search" aria-label="Search" value="{{ search_query }}">
        <button class="btn btn-outline-dark" type="submit">Search</button>
    </form>
    
    <div class="d-flex justify-content-center flex-row" style="min-height: max-content; min-width: max-content;">
        <div class="d-flex justify-content-center flex-column" style="padding: 0;">
            {% if search_query %}
            <h5 style="text-align: center; margin-top: 1rem;">
                Hasil Pencarian "{{ search_query }}"
            </h5>
            {% else %}
            <h5 style="text-align: center; margin-top: 1rem;">Masukkan input di kolom pencarian!</h5>
            {% endif %}
            <div class="result-box">
                {% if data %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Tipe</th>
                                <th>Judul</th>
                                <th>Oleh</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for d in data %}
                                <tr>
                                    <td>{{ d.jenis }}</td>
                                    <td>{{ d.judul }}</td>
                                    <td>{{ d.nama }}</td>
                                    <td>
                                        {% if d.jenis == 'Song' %}
                                            <a href="{% url 'play_song:song' d.id %}" class="btn btn-info btn-action">Lihat</a>
                                        {% elif d.jenis == 'User Playlist' %}
                                            <a href="{% url 'kelola_playlist:play_playlist' d.id %}" class="btn btn-info btn-action">Lihat</a>
                                        {% elif d.jenis == 'Podcast' %}
                                            <a href="{% url 'kelola_podcast:podcast_detail' d.id %}" class="btn btn-info btn-action">Lihat</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    {% if search_query %}
                        <p>Maaf, pencarian untuk "{{ search_query }}" tidak ditemukan</p>
                    {% endif %}

                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}